Separate snort cron/download/update to support different rule sets.

diff --git a/scripts/vyatta-proc-snort-updates b/scripts/vyatta-proc-snort-updates
--- a/scripts/vyatta-proc-snort-updates
+++ b/scripts/vyatta-proc-snort-updates
@@ -1,10 +1,34 @@
 #!/bin/bash
+#
+# Module: vyatta-proc-snort-updates
+# 
+# **** License ****
+# This program is free software; you can redistribute it and/or modify
+# it under the terms of the GNU General Public License version 2 as
+# published by the Free Software Foundation.
+# 
+# This program is distributed in the hope that it will be useful, but
+# WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
+# General Public License for more details.
+# 
+# This code was originally developed by Vyatta, Inc.
+# Portions created by Vyatta are Copyright (C) 2008-2010 Vyatta, Inc.
+# All Rights Reserved.
+# 
+# Author: An-Cheng Huang
+# Date: May 2008
+# Description: process snort update
+# 
+# **** End License ****
+#
+
+NEW_SNORT_UPDATE_FILE=$1
 
 BASE_DIR='/opt/vyatta/etc/ips'
 WORK_DIR="$BASE_DIR/work"
 BACKUP_DIR="$BASE_DIR/backup"
 LOG_FILE="$BASE_DIR/update.log"
-URL_PREFIX='http://www.snort.org/pub-bin/oinkmaster.cgi'
 SNORT_UPDATE_FILE='snortrules-snapshot-2.8.tar'
 CUR_TIME=$(date +%F-%H%M%S)
 LAST_UPDATE_STATUS_FILE="$BASE_DIR/lastupdatestatus"
@@ -24,26 +48,20 @@ abort_updates ()
   log_message "$*"
   log_message 'Update aborted due to error. IPS rules not updated.'
   echo update failed at `date` > $LAST_UPDATE_STATUS_FILE
+  rm -f $BASE_DIR/SNORT_UPDATE_FILE.gz
+  rm -f $WORK_DIR/SNORT_UPDATE_FILE
   exit 1
 }
 
-# get auto-update configuration
-AU_CFG=($(/opt/vyatta/sbin/vyatta-update-snort.pl get-auto-update))
-OINK_CODE=${AU_CFG[0]}
-UPD_HOUR=${AU_CFG[1]}
-
-if [ "$UPD_HOUR" == "NONE" ]; then
-  # not configured. do nothing.
-  exit 0
+if [ ! -f $NEW_SNORT_UPDATE_FILE ]; then
+  log_message 'Update file missing.'
+  exit 1
 fi
 
-# note: since auto-update is configured, ips must be configured.
-#       so the current config can't be antivirus-only.
-
-cur_hour=$(date +%-H)
-if [ "$cur_hour" != "$UPD_HOUR" ]; then
-  # not the right hour. do nothing.
-  exit 0
+file_type=$(file -ib $NEW_SNORT_UPDATE_FILE)
+if [ "$file_type" != "application/x-gzip" ]; then
+  log_message "Invalid file type [$file_type]."
+  exit 1
 fi
 
 mkdir -p $BASE_DIR
@@ -59,10 +77,7 @@ if [ -f $SNORT_UPDATE_FILE.gz ]; then
   rm -f $SNORT_UPDATE_FILE.gz
 fi
 
-# get the update file
-if ! /usr/bin/wget -O $SNORT_UPDATE_FILE.gz -q $URL_PREFIX/$OINK_CODE/$SNORT_UPDATE_FILE.gz; then
-  abort_updates "Failed to get $URL_PREFIX/$OINK_CODE/$SNORT_UPDATE_FILE.gz"
-fi
+mv $NEW_SNORT_UPDATE_FILE $BASE_DIR
 
 new_md5=$(/usr/bin/md5sum $SNORT_UPDATE_FILE.gz)
 if [ "$old_md5" == "$new_md5" ]; then
@@ -81,6 +96,13 @@ fi
 
 # extract
 gunzip $SNORT_UPDATE_FILE.gz >&/dev/null
+
+file_type=$(file -ib $SNORT_UPDATE_FILE)
+if [ "$file_type" != "application/x-tar" ]; then
+  log_message "Invalid file type [$file_type]."
+  exit 1
+fi
+
 tar xf $SNORT_UPDATE_FILE >&/dev/null
 
 # now we have the following directories
@@ -187,5 +209,6 @@ fi
 echo update succeeded at `date` > $LAST_UPDATE_STATUS_FILE
 log_message 'IPS rules update completed successfully'
 log_message "Original rules are moved to $BACKUP_DIR/snort.$CUR_TIME"
+rm -f $WORK_DIR/SNORT_UPDATE_FILE
 exit 0
 
